package plugin

import (
	_ "github.com/chainreactors/zombie/plugin/ftp"
	_ "github.com/chainreactors/zombie/plugin/http"
	_ "github.com/chainreactors/zombie/plugin/ldap"
	_ "github.com/chainreactors/zombie/plugin/memcache"
	_ "github.com/chainreactors/zombie/plugin/mongo"
	_ "github.com/chainreactors/zombie/plugin/mq"
	_ "github.com/chainreactors/zombie/plugin/mssql"
	_ "github.com/chainreactors/zombie/plugin/mysql"
	_ "github.com/chainreactors/zombie/plugin/neutron"
	_ "github.com/chainreactors/zombie/plugin/oracle"
	_ "github.com/chainreactors/zombie/plugin/pop3"
	_ "github.com/chainreactors/zombie/plugin/postgre"
	_ "github.com/chainreactors/zombie/plugin/rdp"
	_ "github.com/chainreactors/zombie/plugin/redis"
	_ "github.com/chainreactors/zombie/plugin/rsync"
	_ "github.com/chainreactors/zombie/plugin/smb"
	_ "github.com/chainreactors/zombie/plugin/snmp"
	_ "github.com/chainreactors/zombie/plugin/socks5"
	_ "github.com/chainreactors/zombie/plugin/ssh"
	_ "github.com/chainreactors/zombie/plugin/vnc"
	_ "github.com/chainreactors/zombie/plugin/zookeeper"
)
